services:
   _defaults:
      autoconfigure: true
      autowire: true
      public: false

   Boelter\LeadsOptin\EventListener\DataContainer\Lead: ~

   Boelter\LeadsOptin\EventListener\DataContainer\Form:
      arguments:
         - '@database_connection'

   Boelter\LeadsOptin\EventListener\DataContainer\Module:
      arguments:
         - '@database_connection'
