services:
   _defaults:
      autoconfigure: true
      autowire: true
      public: false

   Cgoit\LeadsOptinBundle\EventListener\DataContainer\Lead: ~

   Cgoit\LeadsOptinBundle\EventListener\DataContainer\Form:
      arguments:
         - '@database_connection'

   Cgoit\LeadsOptinBundle\EventListener\DataContainer\Module:
      arguments:
         - '@database_connection'
