services:
   _defaults:
      autoconfigure: true
      autowire: true
      public: false

   Boelter\LeadsOptin\Controller\Module\LeadsOptInModule:
      arguments:
         - '@Terminal42\NotificationCenterBundle\NotificationCenter'
         - '@Terminal42\NotificationCenterBundle\Util\FileUploadNormalizer'
         - '@database_connection'
         - '@Codefog\HasteBundle\StringParser'
